version: '3.8'

services:

  mysqlbackempresa:
    image: mysql:latest
    container_name: mysqlRFAF
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: RfafDB
    ports:
      - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysqlRFAF
    environment:
      PMA_HOST: mysqlRFAF
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  backempresaapplication:
    image: rubenyera12/rfaf
    container_name: rfafApplication
    ports:
      - "8080:8080"
    depends_on:

      - "mysqlRFAF"
    environment:
      spring.datasource.url: jdbc:mysql://mysqlRFAF:3306/RfafDB